name: Suchen
favicon: null
layout_spectrum: 0.9537957333959639
typography_spectrum: 0.6303047509863973
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6428110781125724
  lightness: 0.1881753308698535
  saturation: 0.634979878552258
  rhythmicContrast: 0.028270484879612923
purpose: []
